
package src.main.java;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WS_211SanDiego", targetNamespace = "http://ClearViewPortal.com/211SanDiego/", wsdlLocation = "http://211sandiego.clearviewportal.com/ClearViewWS/CustomServices/WS_211SanDiego.asmx?WSDL")
public class WS211SanDiego
    extends Service
{

    private final static URL WS211SANDIEGO_WSDL_LOCATION;
    private final static WebServiceException WS211SANDIEGO_EXCEPTION;
    private final static QName WS211SANDIEGO_QNAME = new QName("http://ClearViewPortal.com/211SanDiego/", "WS_211SanDiego");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://211sandiego.clearviewportal.com/ClearViewWS/CustomServices/WS_211SanDiego.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WS211SANDIEGO_WSDL_LOCATION = url;
        WS211SANDIEGO_EXCEPTION = e;
    }

    public WS211SanDiego() {
        super(__getWsdlLocation(), WS211SANDIEGO_QNAME);
    }

    public WS211SanDiego(WebServiceFeature... features) {
        super(__getWsdlLocation(), WS211SANDIEGO_QNAME, features);
    }

    public WS211SanDiego(URL wsdlLocation) {
        super(wsdlLocation, WS211SANDIEGO_QNAME);
    }

    public WS211SanDiego(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WS211SANDIEGO_QNAME, features);
    }

    public WS211SanDiego(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WS211SanDiego(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WS211SanDiegoSoap
     */
    @WebEndpoint(name = "WS_211SanDiegoSoap")
    public WS211SanDiegoSoap getWS211SanDiegoSoap() {
        return super.getPort(new QName("http://ClearViewPortal.com/211SanDiego/", "WS_211SanDiegoSoap"), WS211SanDiegoSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WS211SanDiegoSoap
     */
    @WebEndpoint(name = "WS_211SanDiegoSoap")
    public WS211SanDiegoSoap getWS211SanDiegoSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://ClearViewPortal.com/211SanDiego/", "WS_211SanDiegoSoap"), WS211SanDiegoSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WS211SANDIEGO_EXCEPTION!= null) {
            throw WS211SANDIEGO_EXCEPTION;
        }
        return WS211SANDIEGO_WSDL_LOCATION;
    }

}
