
package src.main.java;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WS_211SanDiegoSoap", targetNamespace = "http://ClearViewPortal.com/211SanDiego/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WS211SanDiegoSoap {


    /**
     * Test a connection to the 211 San Diego Web Service
     * 
     * @param authHeader
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "TestConnection", action = "http://ClearViewPortal.com/211SanDiego/TestConnection")
    @WebResult(name = "TestConnectionResult", targetNamespace = "http://ClearViewPortal.com/211SanDiego/")
    @RequestWrapper(localName = "TestConnection", targetNamespace = "http://ClearViewPortal.com/211SanDiego/", className = "src.main.java.TestConnection")
    @ResponseWrapper(localName = "TestConnectionResponse", targetNamespace = "http://ClearViewPortal.com/211SanDiego/", className = "src.main.java.TestConnectionResponse")
    public boolean testConnection(
        @WebParam(name = "AuthHeader", targetNamespace = "http://ClearViewPortal.com/211SanDiego/", header = true, partName = "AuthHeader")
        AuthHeader authHeader);

    /**
     * Get the last day imported.  Returns '1/1/1900' if no custom data has been imported.
     * 
     * @param authHeader
     * @param acdName
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod(operationName = "GetLastCustomDataImportDate", action = "http://ClearViewPortal.com/211SanDiego/GetLastCustomDataImportDate")
    @WebResult(name = "GetLastCustomDataImportDateResult", targetNamespace = "http://ClearViewPortal.com/211SanDiego/")
    @RequestWrapper(localName = "GetLastCustomDataImportDate", targetNamespace = "http://ClearViewPortal.com/211SanDiego/", className = "src.main.java.GetLastCustomDataImportDate")
    @ResponseWrapper(localName = "GetLastCustomDataImportDateResponse", targetNamespace = "http://ClearViewPortal.com/211SanDiego/", className = "src.main.java.GetLastCustomDataImportDateResponse")
    public XMLGregorianCalendar getLastCustomDataImportDate(
        @WebParam(name = "ACDName", targetNamespace = "http://ClearViewPortal.com/211SanDiego/")
        String acdName,
        @WebParam(name = "AuthHeader", targetNamespace = "http://ClearViewPortal.com/211SanDiego/", header = true, partName = "AuthHeader")
        AuthHeader authHeader);

    /**
     * Get the last custom data id imported.  Returns 0 if no custom data has been imported.
     * 
     * @param authHeader
     * @param acdName
     * @return
     *     returns long
     */
    @WebMethod(operationName = "GetLastCustomDataID", action = "http://ClearViewPortal.com/211SanDiego/GetLastCustomDataID")
    @WebResult(name = "GetLastCustomDataIDResult", targetNamespace = "http://ClearViewPortal.com/211SanDiego/")
    @RequestWrapper(localName = "GetLastCustomDataID", targetNamespace = "http://ClearViewPortal.com/211SanDiego/", className = "src.main.java.GetLastCustomDataID")
    @ResponseWrapper(localName = "GetLastCustomDataIDResponse", targetNamespace = "http://ClearViewPortal.com/211SanDiego/", className = "src.main.java.GetLastCustomDataIDResponse")
    public long getLastCustomDataID(
        @WebParam(name = "ACDName", targetNamespace = "http://ClearViewPortal.com/211SanDiego/")
        String acdName,
        @WebParam(name = "AuthHeader", targetNamespace = "http://ClearViewPortal.com/211SanDiego/", header = true, partName = "AuthHeader")
        AuthHeader authHeader);

    /**
     * Import custom data into ClearView
     * 
     * @param authHeader
     * @param customDataCollection
     * @return
     *     returns src.main.java.ArrayOfErrorNotifications
     */
    @WebMethod(operationName = "ImportCustomData", action = "http://ClearViewPortal.com/211SanDiego/ImportCustomData")
    @WebResult(name = "ImportCustomDataResult", targetNamespace = "http://ClearViewPortal.com/211SanDiego/")
    @RequestWrapper(localName = "ImportCustomData", targetNamespace = "http://ClearViewPortal.com/211SanDiego/", className = "src.main.java.ImportCustomData")
    @ResponseWrapper(localName = "ImportCustomDataResponse", targetNamespace = "http://ClearViewPortal.com/211SanDiego/", className = "src.main.java.ImportCustomDataResponse")
    public ArrayOfErrorNotifications importCustomData(
        @WebParam(name = "CustomDataCollection", targetNamespace = "http://ClearViewPortal.com/211SanDiego/")
        ArrayOfCustomData customDataCollection,
        @WebParam(name = "AuthHeader", targetNamespace = "http://ClearViewPortal.com/211SanDiego/", header = true, partName = "AuthHeader")
        AuthHeader authHeader);

    /**
     * Get the last day imported.  Returns '1/1/1900' if no custom time has been imported.
     * 
     * @param authHeader
     * @param acdName
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod(operationName = "GetLastCustomTimeImportDate", action = "http://ClearViewPortal.com/211SanDiego/GetLastCustomTimeImportDate")
    @WebResult(name = "GetLastCustomTimeImportDateResult", targetNamespace = "http://ClearViewPortal.com/211SanDiego/")
    @RequestWrapper(localName = "GetLastCustomTimeImportDate", targetNamespace = "http://ClearViewPortal.com/211SanDiego/", className = "src.main.java.GetLastCustomTimeImportDate")
    @ResponseWrapper(localName = "GetLastCustomTimeImportDateResponse", targetNamespace = "http://ClearViewPortal.com/211SanDiego/", className = "src.main.java.GetLastCustomTimeImportDateResponse")
    public XMLGregorianCalendar getLastCustomTimeImportDate(
        @WebParam(name = "ACDName", targetNamespace = "http://ClearViewPortal.com/211SanDiego/")
        String acdName,
        @WebParam(name = "AuthHeader", targetNamespace = "http://ClearViewPortal.com/211SanDiego/", header = true, partName = "AuthHeader")
        AuthHeader authHeader);

    /**
     * Get the last custom time id imported.  Returns 0 if no custom data has been imported.
     * 
     * @param authHeader
     * @param acdName
     * @return
     *     returns long
     */
    @WebMethod(operationName = "GetLastCustomTimeID", action = "http://ClearViewPortal.com/211SanDiego/GetLastCustomTimeID")
    @WebResult(name = "GetLastCustomTimeIDResult", targetNamespace = "http://ClearViewPortal.com/211SanDiego/")
    @RequestWrapper(localName = "GetLastCustomTimeID", targetNamespace = "http://ClearViewPortal.com/211SanDiego/", className = "src.main.java.GetLastCustomTimeID")
    @ResponseWrapper(localName = "GetLastCustomTimeIDResponse", targetNamespace = "http://ClearViewPortal.com/211SanDiego/", className = "src.main.java.GetLastCustomTimeIDResponse")
    public long getLastCustomTimeID(
        @WebParam(name = "ACDName", targetNamespace = "http://ClearViewPortal.com/211SanDiego/")
        String acdName,
        @WebParam(name = "AuthHeader", targetNamespace = "http://ClearViewPortal.com/211SanDiego/", header = true, partName = "AuthHeader")
        AuthHeader authHeader);

    /**
     * Import custom time into ClearView
     * 
     * @param authHeader
     * @param customTimeCollection
     * @return
     *     returns src.main.java.ArrayOfErrorNotifications
     */
    @WebMethod(operationName = "ImportCustomTime", action = "http://ClearViewPortal.com/211SanDiego/ImportCustomTime")
    @WebResult(name = "ImportCustomTimeResult", targetNamespace = "http://ClearViewPortal.com/211SanDiego/")
    @RequestWrapper(localName = "ImportCustomTime", targetNamespace = "http://ClearViewPortal.com/211SanDiego/", className = "src.main.java.ImportCustomTime")
    @ResponseWrapper(localName = "ImportCustomTimeResponse", targetNamespace = "http://ClearViewPortal.com/211SanDiego/", className = "src.main.java.ImportCustomTimeResponse")
    public ArrayOfErrorNotifications importCustomTime(
        @WebParam(name = "CustomTimeCollection", targetNamespace = "http://ClearViewPortal.com/211SanDiego/")
        ArrayOfCustomTime customTimeCollection,
        @WebParam(name = "AuthHeader", targetNamespace = "http://ClearViewPortal.com/211SanDiego/", header = true, partName = "AuthHeader")
        AuthHeader authHeader);

}
